package com.sample
 
import javax.swing.*;
import java.awt.*;
import com.sample.DroolsTest.Message;

global JPanel panel;
global JLabel label;
global JButton button;
global JRadioButton r1;
global JRadioButton r2;
global JRadioButton r3;

declare enum AnswerNames
	YES_MONEY("Yes"), NO_MONEY("No");
	fullName : String
end

declare Answer
	answer : AnswerNames;
end

declare Question
	qText : String;
	numOfAnswers : int;
	answer1 : Answer;
	answer2 : Answer;
	answer3 : Answer;
end

rule "Ask Question"
when
	q : Question();
then
	label.setText(q.getQText());
	r1.setText(q.getAnswer1().getAnswer().getFullName());
	r2.setText(q.getAnswer2().getAnswer().getFullName());
	if(q.getNumOfAnswers() == 3){
		r3.setText(q.getAnswer3().getAnswer().getFullName());
		r3.setVisible(true);
		r3.setEnabled(true);
	}
	else{
		r3.setVisible(false);
		r3.setEnabled(false);
	}
	int result = DroolsTest.ShowQuestion(panel, r1, r2, r3);
	System.out.println("Question asked!");
	System.out.println("Result: " + Integer.toString(result));
	// Tutaj jeszce musi wstawiac odpowiedni fakt odpowiedzi na podstawie otrzymanego inta
	if(result == 1){
		insert(q.getAnswer1().getAnswer());
	}
	else if(result == 2){
		insert(q.getAnswer2().getAnswer());
	}
	else if(result == 3){
		insert(q.getAnswer3().getAnswer());
	}
	// Usuwa fakt pytania z pamieci (chociaz to nie jest calkowicie konieczne?)
	retract(q);
end

rule "Do you love Money"
when
	not Answer(answer == AnswerNames.YES_MONEY);
	not Answer(answer == AnswerNames.NO_MONEY);
then
	System.out.println("Money");
	Question q = new Question("Do you love money?", 2, new Answer(AnswerNames.YES_MONEY), new Answer(AnswerNames.NO_MONEY), null);
	insert(q);
end

